name: 01 - Building Blocks
on: 
  - push
  - workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Say, Hello!"
    
  my-seocond-job:
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - run: echo "I will fail"
      - run: echo "goodbye"

