name: 01 - Building Blocks
on: 
  - push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "Say, Hello!"
    
  my-seocond-job:
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - name: Failed step
        run: echo "goodbye"

