name: 02 - Workflow Events
on: 
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Event Name
        run: |
          echo "Event Name ${{github.event_name}}"



  



