name: 04 - Using Actions
on:
    - workflow_dispatch
jobs:
    using-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - name: Install Dependencies
              run: npm ci

              