name: 04 - Using Actions
on:
    - workflow_dispatch
jobs:
    using-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Print Folder
              run: ls