name: 06-contexts
on:
    - push
    - workflow_dispatch

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "The Event Name is ${{ github.event_name }}"
                echo "The Ref is ${{ github.ref }}"
                echo "The actor that triggered the workflow is ${{ github.actor }}"
                echo "The SHA of the commit that triggered the workflow is ${{ github.sha }}"
                echo "The Workflow is ${{ github.workflow }}"
                echo "The run ID is ${{ github.run_id }}"
                echo "The run number is ${{ github.run_number }}"